# Generated by Django 6.0.5 on 2026-05-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
