# Generated by Django 6.0.5 on 2026-06-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_gender_product_is_archived_and_more'),
        ('store', '0003_remove_order_coupon_delete_coupon'),
    ]

    operations = [
    ]
