# Generated by Django 6.0.5 on 2026-08-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_review_product_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rear_view',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sideView2',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_view1',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_view',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
